### ISSUE TITLE
Shaping bug with 0D7B chillu n, 0D4D virama, 0D31 rra

### ISSUE THREAD

**Issue by davelab6** [smc/manjari#2]
First reported by @cibu in Google internal bug tracker b/158344913 and replied to by ikopylov and @marekjez86

>>> Specific text: `ൻ്റ` (0D7B chillu n, 0D4D virama, 0D31 rra)
>>>
>>> Expected Result: Conjunct should be displayed as per Noto Sans Malayalam. 'ൻ്റ' is a very common conjunct appearing in words for 'mine', 'yours' etc. Without correctly displaying this conjunct, this font is unusable for Malayalam.
>>>
>>> Reference: https://www.unicode.org/versions/Unicode13.0.0/ch12.pdf Page 513 Table 12-39.
>>>
>>> ![158344913-1](https://user-images.githubusercontent.com/261579/86866656-6381b780-c09f-11ea-9f8f-7a2129f95287.png)
>>
>> Here's a fiddle comparing Noto Sans Malayalam to all of our Malayalam fonts on Google Fonts:
>>
>> https://jsfiddle.net/ikopylov/4xw79uat/7/
>> 
>> ![158344913-2](https://user-images.githubusercontent.com/261579/86866657-64b2e480-c09f-11ea-9993-f0ab81fa3dde.png)
>
> Per Cibu's comment and image, Noto Sans (+Serif) is rendering it correctly.... all other fonts have "bugs" (aka issues)
>
> See YT video at https://www.youtube.com/watch?v=tecUaxoFR1c learn how to overcome the issue with the fonts (which I think, I don't speak the language, is blamed on the initial Windows implementations).
>
> These are bugs in all of our Malayalam fonts on Google Fonts.

**Comment by santhoshtr** [comment]
The issue of nta is complicated and a correction proposal was discussed last year: https://www.unicode.org/L2/L2019/19345r2-malayalam-nta.pdf. This was added to Unicode 14, but delayed due to pandemic.

**Comment by cibu** [comment]
Hi Santhosh,

Even though, Liang's proposal was discussed, nothing substantial is getting changed in the standards text. The <CHILLU N, VIRAMA, RRA> remains as the canonical sequence for the akshara in question.  Font developers need to rely on the definitions in the latest version of the standard. Nothing changed regarding this akshara for the last 12 years - since version 5.2 where it was introduced. For the correct Malayalam support, fonts needs to support these common aksharas that are explicitly defined in the standard.

**Comment by davelab6** [comment]
@santhoshtr sir, do you think you would be able to resolve this issue without the unicode update?

**Comment by santhoshtr** [comment]
Fixed in 2c39ae08bcd4e773f646e587bb2e10e94dd71563
